In [36]:
l = [23245,27,546,215,-1234]

In [37]:
l

[23245, 27, 546, 215, -1234]

In [38]:
type(l)

list

In [39]:
import numpy as np

In [40]:
a = np.array(l) #code for create array

In [41]:
a

array([23245,    27,   546,   215, -1234])

In [42]:
#array can't have different data type

In [43]:
b = np.array([12,455,63.3,True,"abc"]) 

In [44]:
b #it will change to string 

array(['12', '455', '63.3', 'True', 'abc'], dtype='<U32')

In [45]:
print(b)

['12' '455' '63.3' 'True' 'abc']


In [46]:
l.pop()

-1234

In [47]:
a.mean()

4559.8

In [48]:
#array has more method than list

In [24]:
#matrix is 2 dimentional of array

---

In [25]:
#Slicing in Arrays

In [49]:
l = [23245,27,546,215]

In [50]:
l

[23245, 27, 546, 215]

In [51]:
l[0:2]

[23245, 27]

In [52]:
#-----

In [53]:
a

array([23245,    27,   546,   215, -1234])

In [54]:
a[2:]

array([  546,   215, -1234])

In [55]:
a[2:4]

array([546, 215])

In [56]:
b = a[2:4] #this is not create a new array but it is a view of a

In [57]:
b

array([546, 215])

In [58]:
b[0]

546

In [59]:
b[:]

array([546, 215])

In [60]:
b[:] = 111

In [61]:
b

array([111, 111])

In [62]:
a

array([23245,    27,   111,   111, -1234])

In [67]:
c = a.copy() #this create new array

In [68]:
c

array([23245,    27,   111,   111, -1234])

In [69]:
c[0] = 1

In [71]:
print(c)
print(a)

[    1    27   111   111 -1234]
[23245    27   111   111 -1234]
